[build]
  command = "npm run build"
  publish = "dist"
[functions]
  directory = "netlify/functions"
[dev]
  publish = "dist"
[[redirects]]
  force = true
  from = "/health/"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"