[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[dev]
  publish = "dist"
[[redirects]]
  force = true
  from = "/health/"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  force = true
  from = "/api/role/*"
  status = 200
  to = "/.netlify/functions/api/role/:splat"